version: "3.9"

networks:
  net-hotel:

volumes:
  sqlserver-data:

services:

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Admin!Sql123"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - net-hotel

  backend:
    build:
      context: ./backend
      target: dev   # 👈 para desarrollo
    container_name: backend
    restart: always
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules   # evita sobrescribir node_modules
    working_dir: /usr/src/app
    command: npm run dev
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=sa
      - DB_PASS=Admin!Sql123
      - DB_NAME=room-map-guru
      - DB_PORT=1433
    networks:
      - net-hotel
    #En producción solo cambias target: prod y command: npm run start.

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"   # 👈 este es el único que expones hacia el host
    networks:
      - net-hotel
